#!/usr/bin/env python3
"""
Global Documentation Builder
Builds global keywords.md, index.md, and comprehensive_book.md
"""

import os
import json
import re
from pathlib import Path
from datetime import datetime
from collections import defaultdict

DOCS_DIR = Path("./docs")
MANIFEST_PATH = DOCS_DIR / "manifest.json"


class GlobalDocBuilder:
    """Builds global documentation files."""

    def __init__(self):
        self.manifest = self._load_manifest()

    def _load_manifest(self):
        """Load manifest file."""
        with open(MANIFEST_PATH, 'r') as f:
            return json.load(f)

    def build_all(self):
        """Build all global documentation files."""
        print("Building global documentation...")

        print("1. Building keywords.md...")
        self.build_keywords_md()

        print("2. Building index.md...")
        self.build_index_md()

        print("3. Building comprehensive_book.md...")
        self.build_comprehensive_book()

        print("\nGlobal documentation complete!")

    def build_keywords_md(self):
        """Build global keywords.md from all _kw.md files."""
        keywords_by_letter = defaultdict(lambda: defaultdict(list))

        # Collect all keywords from _kw.md files
        for kw_file in DOCS_DIR.rglob("*_kw.md"):
            try:
                with open(kw_file, 'r', encoding='utf-8') as f:
                    content = f.read()

                    # Extract keywords and their files
                    # Pattern: **keyword** → [file_docs.md#anchor]
                    matches = re.findall(r'\*\*(\w+)\*\*\s*→\s*\[`([^`]+)`\]', content)

                    for keyword, file_ref in matches[:100]:  # Limit per file
                        first_letter = keyword[0].upper()
                        rel_path = kw_file.relative_to(DOCS_DIR)
                        doc_path = kw_file.parent / file_ref
                        rel_doc_path = doc_path.relative_to(DOCS_DIR)

                        keywords_by_letter[first_letter][keyword].append(str(rel_doc_path))
            except Exception as e:
                pass

        # Build keywords.md
        keywords_md = f"""# Global Keyword Index

**Generated**: {datetime.utcnow().isoformat()}Z

This is a comprehensive A→Z index of all keywords extracted from the repository.

---

"""

        for letter in sorted(keywords_by_letter.keys()):
            keywords_md += f"\n## {letter}\n\n"

            for keyword in sorted(keywords_by_letter[letter].keys(), key=str.lower):
                files = keywords_by_letter[letter][keyword]
                # Deduplicate and limit
                unique_files = list(set(files))[:5]

                keywords_md += f"### {keyword}\n\n"
                keywords_md += "Found in:\n"
                for file_path in unique_files:
                    keywords_md += f"- [{file_path}](./{file_path})\n"
                keywords_md += "\n"

        # Write keywords.md
        with open(DOCS_DIR / "keywords.md", 'w', encoding='utf-8') as f:
            f.write(keywords_md)

        print(f"  Created keywords.md with {sum(len(kws) for kws in keywords_by_letter.values())} keywords")

    def build_index_md(self):
        """Build root index.md."""
        index_md = f"""# Repository Documentation Index

**Repository**: {self.manifest['repo_name']}
**Commit**: `{self.manifest['repo_fingerprint']}`
**Generated**: {datetime.utcnow().isoformat()}Z

---

## Overview

This documentation was automatically generated by the **World's Best Repo Book Generator**.

### Statistics

- **Total Files**: {self.manifest['file_count']:,}
- **Documentation Files**: {self.manifest.get('docs_count', 0):,}
- **Repository Size**: {self.manifest.get('bytes_written', 0) / 1024 / 1024:.2f} MB

---

## Quick Links

- [Global Keyword Index](./keywords.md)
- [Comprehensive Book](./comprehensive_book.md)
- [Root Documentation](./doc.md)
- [Verification Report](./verification_report.md)

---

## Folder Structure

"""

        # Find all folder index.md files
        folders = []
        for index_file in sorted(DOCS_DIR.rglob("index.md")):
            rel_path = index_file.relative_to(DOCS_DIR)
            if rel_path.name == "index.md" and str(rel_path) != "index.md":
                folder_path = rel_path.parent
                folders.append(folder_path)

        # Organize by depth
        by_depth = defaultdict(list)
        for folder in folders:
            depth = len(folder.parts)
            by_depth[depth].append(folder)

        # Print top-level folders
        index_md += "### Top-Level Folders\n\n"
        for folder in sorted(by_depth.get(1, []) if 1 in by_depth else []):
            index_md += f"- [{folder.name}/](./{folder}/index.md)\n"

        # Print all folders organized
        index_md += "\n### All Folders\n\n"
        for depth in sorted(by_depth.keys())[:5]:  # Limit depth for readability
            for folder in sorted(by_depth[depth]):
                indent = "  " * (depth - 1)
                index_md += f"{indent}- [{folder}](./{folder}/index.md)\n"

        index_md += f"""

---

## How to Use This Documentation

1. **Browse by Folder**: Navigate through the folder structure using the links above
2. **Search by Keyword**: Use the [Global Keyword Index](./keywords.md) to find specific terms
3. **Read the Book**: The [Comprehensive Book](./comprehensive_book.md) provides a narrative walkthrough
4. **File Documentation**: Each file has detailed `_docs.md` and `_kw.md` documentation

---

**Generated by**: World's Best Repo Book Generator v{self.manifest['generator_version']}
"""

        with open(DOCS_DIR / "index.md", 'w', encoding='utf-8') as f:
            f.write(index_md)

        print(f"  Created index.md with {len(folders)} folder links")

    def build_comprehensive_book(self):
        """Build comprehensive_book.md from folder docs."""
        print("  Building comprehensive book (this may take a while)...")

        book = f"""# Comprehensive Repository Book

**Repository**: {self.manifest['repo_name']}
**Commit**: `{self.manifest['repo_fingerprint']}`
**Generated**: {datetime.utcnow().isoformat()}Z

---

## Introduction

This is a comprehensive book generated from the entire repository. It combines all folder documentation into a single narrative document.

---

## Table of Contents

"""

        # Find all doc.md files and organize them
        doc_files = []
        for doc_file in sorted(DOCS_DIR.rglob("doc.md")):
            rel_path = doc_file.relative_to(DOCS_DIR)
            if rel_path.name == "doc.md":
                folder_path = rel_path.parent
                doc_files.append((folder_path, doc_file))

        # Sort by path depth and name
        doc_files.sort(key=lambda x: (len(x[0].parts), str(x[0])))

        # Create table of contents
        for folder_path, _ in doc_files[:100]:  # Limit TOC
            depth = len(folder_path.parts)
            indent = "  " * depth
            folder_name = str(folder_path) if folder_path != Path('.') else 'Root'
            anchor = self._create_anchor(folder_name)
            book += f"{indent}- [{folder_name}](#{anchor})\n"

        book += "\n---\n\n"

        # Add content from each doc.md
        chapters_added = 0
        for folder_path, doc_file in doc_files[:200]:  # Limit to prevent huge file
            try:
                with open(doc_file, 'r', encoding='utf-8') as f:
                    content = f.read()

                    # Remove the title line (first line)
                    lines = content.split('\n')
                    if lines and lines[0].startswith('#'):
                        content = '\n'.join(lines[1:])

                    folder_name = str(folder_path) if folder_path != Path('.') else 'Root'
                    book += f"\n\n## Chapter: {folder_name}\n\n"
                    book += content
                    book += "\n\n---\n\n"

                    chapters_added += 1
            except Exception as e:
                print(f"    Warning: Could not include {folder_path}: {e}")

        book += f"""

---

## Conclusion

This comprehensive book covered {chapters_added} major sections of the repository.

For more detailed information:
- See individual file documentation (`*_docs.md` files)
- Browse the [keyword index](./keywords.md)
- Explore the [folder structure](./index.md)

**End of Book**

---

**Generated by**: World's Best Repo Book Generator v{self.manifest['generator_version']}
"""

        with open(DOCS_DIR / "comprehensive_book.md", 'w', encoding='utf-8') as f:
            f.write(book)

        print(f"  Created comprehensive_book.md with {chapters_added} chapters")

    def _create_anchor(self, text: str) -> str:
        """Create URL-safe anchor from text."""
        anchor = text.lower()
        anchor = re.sub(r'[^a-z0-9_/-]', '-', anchor)
        anchor = re.sub(r'-+', '-', anchor)
        return anchor.strip('-')


def main():
    print("=" * 80)
    print("GLOBAL DOCUMENTATION BUILDER")
    print("=" * 80)

    builder = GlobalDocBuilder()
    builder.build_all()

    print("\n" + "=" * 80)
    print("GLOBAL DOCS COMPLETE")
    print("=" * 80)


if __name__ == '__main__':
    main()
